name = "BoreholeResistance"
uuid = "e68eaff3-538a-4178-bf62-7dbf06caf399"
version = "1.0.0-DEV"
authors = ["Gabriel-Dion <dion.gabriel100@gmail.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
